version: '3.9'

services:
  deezerdl:
    build:
      context: .
    container_name: deezerdl
    restart: unless-stopped
    environment:
      DL_LOCATION: '/downloads'
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      PLAYLIST_ID: ${PLAYLIST_ID}
      YT_PLAYLIST_ID: ${YT_PLAYLIST_ID}
    volumes:
      - ${DL_LOCATION}:/downloads